package incidentiq

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

var (
	wrapperMethodPattern = regexp.MustCompile(`func \(s \*(\w+)\) (\w+)\(ctx`)
	docServicePattern    = regexp.MustCompile(`func \(s \*incidentiq\.(\w+)\)`)
	docMethodPattern     = regexp.MustCompile("(?m)^### `(\\w+)`")
	docAliasPattern      = regexp.MustCompile("(?m)^\\| `client\\.[\\w.]+\\.(\\w+)` \\| `client\\.")
)

type serviceMethod struct {
	service string
	method  string
}

// TestGeneratedReferenceMatchesWrappers keeps docs/sdk-reference honest about
// the Go surface. The reference pages and the wrappers are produced by two
// generators from the same bundled contract artifacts, so a drift here means
// one of them was run without the other.
func TestGeneratedReferenceMatchesWrappers(t *testing.T) {
	wrappers := wrapperMethods(t)
	documented := documentedMethods(t)

	if len(wrappers) == 0 {
		t.Fatal("found no generated wrapper methods")
	}
	for method := range wrappers {
		if !documented[method] {
			t.Errorf("wrapper %s.%s is not documented in docs/sdk-reference; run go generate ./...", method.service, method.method)
		}
	}
	for method := range documented {
		if !wrappers[method] {
			t.Errorf("docs/sdk-reference documents %s.%s, which no generated wrapper provides; run go generate ./...", method.service, method.method)
		}
	}
}

// TestGeneratedReferenceIsGoShaped guards the decoupling from the Python source
// SDK: the reference pages must describe this repository's Go call shape and
// must not reintroduce the source SDK's surface.
//
// The scan covers whole pages, not just the generator's own scaffolding. A
// scaffolding-only scan would pass vacuously if the copied Python pages were
// ever restored wholesale, because those pages contain none of the lines this
// generator writes.
func TestGeneratedReferenceIsGoShaped(t *testing.T) {
	forbidden := []string{
		"Python Arg",
		"await ",
		"client.silver.",
		"client.apps.",
		".raw(",
		"dict[str, Any]",
		"iter_pages",
		"Sync client access",
		"Async client access",
	}
	pages, err := filepath.Glob(filepath.Join("docs", "sdk-reference", "*.md"))
	if err != nil {
		t.Fatalf("glob reference pages: %v", err)
	}
	if len(pages) == 0 {
		t.Fatal("found no reference pages")
	}
	for _, page := range pages {
		contents := readDocPage(t, page)
		if !strings.Contains(contents, "Code generated by scripts/generate_sdk_reference.go") {
			t.Errorf("%s is not generated by scripts/generate_sdk_reference.go; reference pages must not be copied or hand-written", page)
		}
		for _, term := range forbidden {
			for i, line := range strings.Split(contents, "\n") {
				if strings.Contains(line, term) {
					t.Errorf("%s:%d documents the Python surface (%q): %s", page, i+1, term, line)
				}
			}
		}
	}
}

func wrapperMethods(t *testing.T) map[serviceMethod]bool {
	t.Helper()
	methods := map[serviceMethod]bool{}
	for _, source := range []string{"generated_wrappers.go", "silver_user_rooms.go"} {
		contents := readDocPage(t, source)
		for _, match := range wrapperMethodPattern.FindAllStringSubmatch(contents, -1) {
			methods[serviceMethod{service: match[1], method: match[2]}] = true
		}
	}
	return methods
}

func documentedMethods(t *testing.T) map[serviceMethod]bool {
	t.Helper()
	pages, err := filepath.Glob(filepath.Join("docs", "sdk-reference", "*.md"))
	if err != nil {
		t.Fatalf("glob reference pages: %v", err)
	}
	methods := map[serviceMethod]bool{}
	for _, page := range pages {
		contents := readDocPage(t, page)
		service := docServicePattern.FindStringSubmatch(contents)
		if service == nil {
			continue
		}
		for _, match := range docMethodPattern.FindAllStringSubmatch(contents, -1) {
			methods[serviceMethod{service: service[1], method: match[1]}] = true
		}
		for _, match := range docAliasPattern.FindAllStringSubmatch(contents, -1) {
			methods[serviceMethod{service: service[1], method: match[1]}] = true
		}
	}
	return methods
}

func readDocPage(t *testing.T, path string) string {
	t.Helper()
	contents, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(contents)
}
