//go:build ignore

package main

import (
	"fmt"
	"html"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	outputDir := "site"
	if len(os.Args) > 1 {
		outputDir = os.Args[1]
	}
	if err := buildDocsSite(outputDir); err != nil {
		_, _ = fmt.Fprintf(os.Stderr, "build docs site: %v\n", err)
		os.Exit(1)
	}
}

func buildDocsSite(outputDir string) error {
	if err := os.RemoveAll(outputDir); err != nil {
		return err
	}
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		return err
	}

	markdownFiles, err := collectMarkdownFiles()
	if err != nil {
		return err
	}
	for _, source := range markdownFiles {
		destination := filepath.Join(outputDir, source)
		if err := os.MkdirAll(filepath.Dir(destination), 0o755); err != nil {
			return err
		}
		if err := copyFile(source, destination); err != nil {
			return err
		}
	}
	return writeIndex(outputDir, markdownFiles)
}

func collectMarkdownFiles() ([]string, error) {
	var files []string
	err := filepath.WalkDir(".", func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			switch entry.Name() {
			case ".git", ".gocache", ".gomodcache", "dist", "site", "tmp":
				return filepath.SkipDir
			}
			return nil
		}
		if strings.EqualFold(filepath.Ext(path), ".md") {
			files = append(files, strings.TrimPrefix(filepath.ToSlash(path), "./"))
		}
		return nil
	})
	sort.Strings(files)
	return files, err
}

func copyFile(source string, destination string) error {
	input, err := os.Open(source)
	if err != nil {
		return err
	}
	defer input.Close()

	output, err := os.Create(destination)
	if err != nil {
		return err
	}
	defer output.Close()

	_, err = io.Copy(output, input)
	return err
}

func writeIndex(outputDir string, markdownFiles []string) error {
	var builder strings.Builder
	builder.WriteString("<!doctype html>\n<html lang=\"en\">\n<head>\n")
	builder.WriteString("<meta charset=\"utf-8\">\n")
	builder.WriteString("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n")
	builder.WriteString("<title>incidentiq-sdk-golang docs</title>\n")
	builder.WriteString("<style>body{font-family:system-ui,sans-serif;max-width:960px;margin:2rem auto;padding:0 1rem;line-height:1.5}code{background:#f3f4f6;padding:.1rem .25rem;border-radius:4px}li{margin:.25rem 0}</style>\n")
	builder.WriteString("</head>\n<body>\n")
	builder.WriteString("<h1>incidentiq-sdk-golang docs</h1>\n")
	builder.WriteString("<p>This static index is generated by <code>scripts/build_docs_site.go</code>. Markdown files are copied without conversion so GitHub Pages can publish the same checked-in documentation tree used by contributors.</p>\n")
	builder.WriteString("<ul>\n")
	for _, file := range markdownFiles {
		escaped := html.EscapeString(file)
		builder.WriteString("<li><a href=\"")
		builder.WriteString(escaped)
		builder.WriteString("\">")
		builder.WriteString(escaped)
		builder.WriteString("</a></li>\n")
	}
	builder.WriteString("</ul>\n</body>\n</html>\n")
	return os.WriteFile(filepath.Join(outputDir, "index.html"), []byte(builder.String()), 0o644)
}
