//go:build ignore

package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

type goldenOperation struct {
	Method      string `json:"method"`
	Name        string `json:"name"`
	Namespace   string `json:"namespace"`
	OperationID string `json:"operation_id"`
	Path        string `json:"path"`
}

type silverOperation struct {
	HTTPMethod string   `json:"http_method"`
	Name       string   `json:"name"`
	Namespace  string   `json:"namespace"`
	Path       string   `json:"path"`
	Provenance string   `json:"provenance"`
	Sources    []string `json:"sources"`
}

type generatedOperation struct {
	Method    string
	Name      string
	Namespace string
	Path      string
}

type namespaceGroup struct {
	Namespace  string
	FieldName  string
	StructName string
	Operations []generatedOperation
}

var nonIdentifier = regexp.MustCompile(`[^0-9A-Za-z]+`)

func main() {
	golden := readGolden("testdata/contract/golden_sdk_inventory.json")
	silver := readSilver("testdata/contract/silver_sdk_inventory.json")

	var out bytes.Buffer
	out.WriteString("// Code generated by scripts/generate_wrappers.go; DO NOT EDIT.\n")
	out.WriteString("\npackage incidentiq\n\n")
	out.WriteString("import \"context\"\n\n")
	writeClientFields(&out, groupOperations(golden, "Golden"))
	writeRoot(&out, "Silver", groupOperations(silver, "Silver"))
	writeWireFunction(&out, groupOperations(golden, "Golden"), groupOperations(silver, "Silver"))
	writeInventoryFunctions(&out, golden, silver)

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		_, _ = os.Stderr.Write(out.Bytes())
		fatal("format generated source: %v", err)
	}
	if err := os.WriteFile("generated_wrappers.go", formatted, 0o644); err != nil {
		fatal("write generated_wrappers.go: %v", err)
	}
}

func readGolden(path string) []generatedOperation {
	payload, err := os.ReadFile(path)
	if err != nil {
		fatal("read %s: %v", path, err)
	}
	var raw []goldenOperation
	if err := json.Unmarshal(payload, &raw); err != nil {
		fatal("parse %s: %v", path, err)
	}
	ops := make([]generatedOperation, 0, len(raw))
	for _, op := range raw {
		ops = append(ops, generatedOperation{
			Method:    op.Method,
			Name:      op.Name,
			Namespace: op.Namespace,
			Path:      op.Path,
		})
	}
	return ops
}

func readSilver(path string) []generatedOperation {
	payload, err := os.ReadFile(path)
	if err != nil {
		fatal("read %s: %v", path, err)
	}
	var raw []silverOperation
	if err := json.Unmarshal(payload, &raw); err != nil {
		fatal("parse %s: %v", path, err)
	}
	ops := make([]generatedOperation, 0, len(raw))
	for _, op := range raw {
		ops = append(ops, generatedOperation{
			Method:    op.HTTPMethod,
			Name:      op.Name,
			Namespace: op.Namespace,
			Path:      op.Path,
		})
	}
	return ops
}

func groupOperations(ops []generatedOperation, prefix string) []namespaceGroup {
	byNamespace := map[string][]generatedOperation{}
	for _, op := range ops {
		byNamespace[op.Namespace] = append(byNamespace[op.Namespace], op)
	}
	namespaces := make([]string, 0, len(byNamespace))
	for namespace := range byNamespace {
		namespaces = append(namespaces, namespace)
	}
	sort.Strings(namespaces)
	groups := make([]namespaceGroup, 0, len(namespaces))
	for _, namespace := range namespaces {
		groupOps := byNamespace[namespace]
		sort.Slice(groupOps, func(i, j int) bool {
			return groupOps[i].Name < groupOps[j].Name
		})
		fieldName := exportedName(namespace)
		groups = append(groups, namespaceGroup{
			Namespace:  namespace,
			FieldName:  fieldName,
			StructName: prefix + fieldName + "Service",
			Operations: groupOps,
		})
	}
	return groups
}

func writeRoot(out *bytes.Buffer, prefix string, groups []namespaceGroup) {
	fmt.Fprintf(out, "type %sClient struct {\n", prefix)
	for _, group := range groups {
		fmt.Fprintf(out, "\t%s *%s\n", group.FieldName, group.StructName)
	}
	out.WriteString("}\n\n")
	for _, group := range groups {
		fmt.Fprintf(out, "type %s struct { client *Client }\n\n", group.StructName)
		for _, op := range group.Operations {
			fmt.Fprintf(out, "func (s *%s) %s(ctx context.Context, opts RequestOptions, out any) error {\n", group.StructName, exportedName(op.Name))
			fmt.Fprintf(out, "\treturn s.client.Request(ctx, %q, %q, opts, out)\n", op.Method, op.Path)
			out.WriteString("}\n\n")
		}
	}
}

func writeClientFields(out *bytes.Buffer, groups []namespaceGroup) {
	out.WriteString("type generatedClientServices struct {\n")
	for _, group := range groups {
		fmt.Fprintf(out, "\t%s *%s\n", group.FieldName, group.StructName)
	}
	out.WriteString("}\n\n")
	for _, group := range groups {
		fmt.Fprintf(out, "type %s struct { client *Client }\n\n", group.StructName)
		for _, op := range group.Operations {
			fmt.Fprintf(out, "func (s *%s) %s(ctx context.Context, opts RequestOptions, out any) error {\n", group.StructName, exportedName(op.Name))
			fmt.Fprintf(out, "\treturn s.client.Request(ctx, %q, %q, opts, out)\n", op.Method, op.Path)
			out.WriteString("}\n\n")
		}
	}
}

func writeWireFunction(out *bytes.Buffer, golden []namespaceGroup, silver []namespaceGroup) {
	out.WriteString("func wireGeneratedServices(client *Client) {\n")
	out.WriteString("\tclient.generatedClientServices = generatedClientServices{\n")
	for _, group := range golden {
		fmt.Fprintf(out, "\t\t%s: &%s{client: client},\n", group.FieldName, group.StructName)
	}
	out.WriteString("\t}\n")
	out.WriteString("\tclient.Silver = &SilverClient{\n")
	for _, group := range silver {
		fmt.Fprintf(out, "\t\t%s: &%s{client: client},\n", group.FieldName, group.StructName)
	}
	out.WriteString("\t}\n")
	out.WriteString("}\n\n")
}

func writeInventoryFunctions(out *bytes.Buffer, golden []generatedOperation, silver []generatedOperation) {
	writeWrapperNames(out, "Golden", golden)
	writeWrapperNames(out, "Silver", silver)
}

func writeWrapperNames(out *bytes.Buffer, prefix string, ops []generatedOperation) {
	sort.Slice(ops, func(i, j int) bool {
		left := ops[i].Namespace + "." + ops[i].Name
		right := ops[j].Namespace + "." + ops[j].Name
		return left < right
	})
	fmt.Fprintf(out, "func %sWrapperInventory() []string {\n", prefix)
	out.WriteString("\treturn []string{\n")
	for _, op := range ops {
		fmt.Fprintf(out, "\t\t%q,\n", op.Namespace+"."+op.Name)
	}
	out.WriteString("\t}\n")
	out.WriteString("}\n\n")
}

func exportedName(value string) string {
	parts := strings.Fields(nonIdentifier.ReplaceAllString(value, " "))
	if len(parts) == 0 {
		return "Value"
	}
	for i, part := range parts {
		parts[i] = exportPart(part)
	}
	name := strings.Join(parts, "")
	if name == "" {
		return "Value"
	}
	if unicode.IsDigit(rune(name[0])) {
		name = "N" + name
	}
	return name
}

func exportPart(value string) string {
	if value == "" {
		return ""
	}
	runes := []rune(value)
	for i, r := range runes {
		if i == 0 {
			runes[i] = unicode.ToUpper(r)
			continue
		}
		runes[i] = unicode.ToLower(r)
	}
	return string(runes)
}

func fatal(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
