//go:build ignore

package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"sort"
	"strings"
	"unicode"
)

type goldenOperation struct {
	Method      string `json:"method"`
	Name        string `json:"name"`
	Namespace   string `json:"namespace"`
	OperationID string `json:"operation_id"`
	Path        string `json:"path"`
}

type silverOperation struct {
	HTTPMethod string   `json:"http_method"`
	Name       string   `json:"name"`
	Namespace  string   `json:"namespace"`
	Path       string   `json:"path"`
	Provenance string   `json:"provenance"`
	Sources    []string `json:"sources"`
}

type typedSilverMethod struct {
	Namespace string `json:"namespace"`
	Name      string `json:"name"`
}

type generatedOperation struct {
	Method    string
	Name      string
	Namespace string
	Path      string
}

type namespaceGroup struct {
	Namespace  string
	FieldName  string
	StructName string
	Operations []generatedOperation
	Aliases    []generatedAlias
}

type legacyAlias struct {
	LegacyName      string `json:"legacy_name"`
	LegacyNamespace string `json:"legacy_namespace"`
	Surface         string `json:"surface"`
	TargetName      string `json:"target_name"`
	TargetNamespace string `json:"target_namespace"`
}

type legacyAliasBundle struct {
	Aliases []legacyAlias `json:"aliases"`
}

// generatedAlias is a deprecated forwarder from a pre-migration method name to
// the method the new contract moved it to.
type generatedAlias struct {
	Name    string
	Target  string
	Display string
}

type nestedNamespaceGroup struct {
	Namespace string
	FieldName string
	Children  []namespaceGroup
}

var nonIdentifier = regexp.MustCompile(`[^0-9A-Za-z]+`)
var typedSilverMethods map[string]bool

func main() {
	golden := readGolden("testdata/contract/golden_sdk_inventory.json")
	silver := readSilver("testdata/contract/silver_sdk_inventory.json")
	typedSilverMethods = readTypedSilverMethods("data/typed_silver_methods.json")
	aliases := readAliases("data/legacy/aliases.json")

	goldenGroups := groupOperations(golden, "Golden")
	silverGroups := groupOperations(silver, "Silver")
	goldenGroups = attachAliases(goldenGroups, silverGroups, aliases)

	var out bytes.Buffer
	out.WriteString("// Code generated by scripts/generate_wrappers.go; DO NOT EDIT.\n")
	out.WriteString("\npackage incidentiq\n\n")
	out.WriteString("import \"context\"\n\n")
	writeClientFields(&out, goldenGroups)
	writeSilverRoot(&out, silverGroups)
	writeWireFunction(&out, goldenGroups, silverGroups)
	writeInventoryFunctions(&out, golden, silver)

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		_, _ = os.Stderr.Write(out.Bytes())
		fatal("format generated source: %v", err)
	}
	if err := os.WriteFile("generated_wrappers.go", formatted, 0o644); err != nil {
		fatal("write generated_wrappers.go: %v", err)
	}
}

func readTypedSilverMethods(path string) map[string]bool {
	payload, err := os.ReadFile(path)
	if err != nil {
		fatal("read %s: %v", path, err)
	}
	var raw []typedSilverMethod
	if err := json.Unmarshal(payload, &raw); err != nil {
		fatal("parse %s: %v", path, err)
	}
	methods := make(map[string]bool, len(raw))
	for _, method := range raw {
		methods[method.Namespace+"."+method.Name] = true
	}
	return methods
}

func readGolden(path string) []generatedOperation {
	payload, err := os.ReadFile(path)
	if err != nil {
		fatal("read %s: %v", path, err)
	}
	var raw []goldenOperation
	if err := json.Unmarshal(payload, &raw); err != nil {
		fatal("parse %s: %v", path, err)
	}
	ops := make([]generatedOperation, 0, len(raw))
	for _, op := range raw {
		ops = append(ops, generatedOperation{
			Method:    op.Method,
			Name:      op.Name,
			Namespace: op.Namespace,
			Path:      op.Path,
		})
	}
	return ops
}

func readSilver(path string) []generatedOperation {
	payload, err := os.ReadFile(path)
	if err != nil {
		fatal("read %s: %v", path, err)
	}
	var raw []silverOperation
	if err := json.Unmarshal(payload, &raw); err != nil {
		fatal("parse %s: %v", path, err)
	}
	ops := make([]generatedOperation, 0, len(raw))
	for _, op := range raw {
		ops = append(ops, generatedOperation{
			Method:    op.HTTPMethod,
			Name:      op.Name,
			Namespace: op.Namespace,
			Path:      op.Path,
		})
	}
	return ops
}

func readAliases(path string) []legacyAlias {
	payload, err := os.ReadFile(path)
	if err != nil {
		fatal("read %s: %v", path, err)
	}
	var bundle legacyAliasBundle
	if err := json.Unmarshal(payload, &bundle); err != nil {
		fatal("parse %s: %v", path, err)
	}
	return bundle.Aliases
}

// silverFieldPaths maps each Silver namespace to the client expression that
// reaches its service, accounting for the nested app namespaces.
func silverFieldPaths(groups []namespaceGroup) map[string]string {
	topLevel, nested := splitNestedGroups(groups)
	paths := map[string]string{}
	for _, group := range topLevel {
		paths[group.Namespace] = "Silver." + group.FieldName
	}
	for _, parent := range nested {
		for _, child := range parent.Children {
			paths[child.Namespace] = "Silver." + parent.FieldName + "." + child.FieldName
		}
	}
	return paths
}

// attachAliases adds deprecated forwarders to the Golden namespace groups,
// creating empty groups for legacy namespaces the new contract dropped. An
// alias never shadows a generated method, so generated names always win.
func attachAliases(golden []namespaceGroup, silver []namespaceGroup, aliases []legacyAlias) []namespaceGroup {
	silverPaths := silverFieldPaths(silver)
	goldenPaths := map[string]string{}
	index := map[string]int{}
	byFieldName := map[string]string{}
	for i, group := range golden {
		if other, ok := byFieldName[group.FieldName]; ok {
			fatal("namespaces %q and %q both export as %q", other, group.Namespace, group.FieldName)
		}
		byFieldName[group.FieldName] = group.Namespace
		index[group.Namespace] = i
		goldenPaths[group.Namespace] = group.FieldName
	}

	sorted := append([]legacyAlias(nil), aliases...)
	sort.Slice(sorted, func(i, j int) bool {
		if sorted[i].LegacyNamespace != sorted[j].LegacyNamespace {
			return sorted[i].LegacyNamespace < sorted[j].LegacyNamespace
		}
		return sorted[i].LegacyName < sorted[j].LegacyName
	})

	for _, alias := range sorted {
		position, ok := index[alias.LegacyNamespace]
		if !ok {
			fieldName := exportedName(alias.LegacyNamespace)
			if other, ok := byFieldName[fieldName]; ok {
				fatal("namespaces %q and %q both export as %q", other, alias.LegacyNamespace, fieldName)
			}
			byFieldName[fieldName] = alias.LegacyNamespace
			golden = append(golden, namespaceGroup{
				Namespace:  alias.LegacyNamespace,
				FieldName:  fieldName,
				StructName: "Golden" + fieldName + "Service",
			})
			position = len(golden) - 1
			index[alias.LegacyNamespace] = position
			goldenPaths[alias.LegacyNamespace] = fieldName
		}

		group := golden[position]
		name := exportedName(alias.LegacyName)
		if nameTaken(group, name) {
			continue
		}

		var target string
		switch alias.Surface {
		case "silver":
			path, ok := silverPaths[alias.TargetNamespace]
			if !ok {
				fatal("alias %s.%s targets unknown Silver namespace %q", alias.LegacyNamespace, alias.LegacyName, alias.TargetNamespace)
			}
			target = path
		case "golden":
			path, ok := goldenPaths[alias.TargetNamespace]
			if !ok {
				fatal("alias %s.%s targets unknown Golden namespace %q", alias.LegacyNamespace, alias.LegacyName, alias.TargetNamespace)
			}
			target = path
		default:
			fatal("alias %s.%s has unknown surface %q", alias.LegacyNamespace, alias.LegacyName, alias.Surface)
		}
		display := target + "." + exportedName(alias.TargetName)

		group.Aliases = append(group.Aliases, generatedAlias{
			Name:    name,
			Target:  "s.client." + display,
			Display: display,
		})
		golden[position] = group
	}

	sort.Slice(golden, func(i, j int) bool { return golden[i].Namespace < golden[j].Namespace })
	return golden
}

func nameTaken(group namespaceGroup, name string) bool {
	for _, op := range group.Operations {
		if exportedName(op.Name) == name {
			return true
		}
	}
	for _, alias := range group.Aliases {
		if alias.Name == name {
			return true
		}
	}
	return false
}

func writeAliases(out *bytes.Buffer, group namespaceGroup) {
	for _, alias := range group.Aliases {
		fmt.Fprintf(out, "// Deprecated: use %s instead. Renamed by the OpenAPI contract\n", alias.Display)
		out.WriteString("// migration; this forwarder will be removed in a future release.\n")
		fmt.Fprintf(out, "func (s *%s) %s(ctx context.Context, opts RequestOptions, out any) error {\n", group.StructName, alias.Name)
		fmt.Fprintf(out, "\treturn %s(ctx, opts, out)\n", alias.Target)
		out.WriteString("}\n\n")
	}
}

func groupOperations(ops []generatedOperation, prefix string) []namespaceGroup {
	byNamespace := map[string][]generatedOperation{}
	for _, op := range ops {
		byNamespace[op.Namespace] = append(byNamespace[op.Namespace], op)
	}
	namespaces := make([]string, 0, len(byNamespace))
	for namespace := range byNamespace {
		namespaces = append(namespaces, namespace)
	}
	sort.Strings(namespaces)
	groups := make([]namespaceGroup, 0, len(namespaces))
	for _, namespace := range namespaces {
		groupOps := byNamespace[namespace]
		sort.Slice(groupOps, func(i, j int) bool {
			return groupOps[i].Name < groupOps[j].Name
		})
		fieldName := exportedName(namespace)
		groups = append(groups, namespaceGroup{
			Namespace:  namespace,
			FieldName:  fieldName,
			StructName: prefix + fieldName + "Service",
			Operations: groupOps,
		})
	}
	return groups
}

func writeRoot(out *bytes.Buffer, prefix string, groups []namespaceGroup) {
	fmt.Fprintf(out, "type %sClient struct {\n", prefix)
	for _, group := range groups {
		fmt.Fprintf(out, "\t%s *%s\n", group.FieldName, group.StructName)
	}
	out.WriteString("}\n\n")
	for _, group := range groups {
		fmt.Fprintf(out, "type %s struct { client *Client }\n\n", group.StructName)
		for _, op := range group.Operations {
			fmt.Fprintf(out, "func (s *%s) %s(ctx context.Context, opts RequestOptions, out any) error {\n", group.StructName, exportedName(op.Name))
			fmt.Fprintf(out, "\treturn s.client.request(ctx, %q, %q, opts, out, true)\n", op.Method, op.Path)
			out.WriteString("}\n\n")
		}
	}
}

func writeSilverRoot(out *bytes.Buffer, groups []namespaceGroup) {
	topLevel, nested := splitNestedGroups(groups)
	out.WriteString("type SilverClient struct {\n")
	for _, group := range topLevel {
		fmt.Fprintf(out, "\t%s *%s\n", group.FieldName, group.StructName)
	}
	for _, group := range nested {
		fmt.Fprintf(out, "\t%s *Silver%sClient\n", group.FieldName, group.FieldName)
	}
	out.WriteString("}\n\n")
	for _, group := range nested {
		fmt.Fprintf(out, "type Silver%sClient struct {\n", group.FieldName)
		for _, child := range group.Children {
			fmt.Fprintf(out, "\t%s *%s\n", child.FieldName, child.StructName)
		}
		out.WriteString("}\n\n")
	}
	for _, group := range append(topLevel, flattenNestedGroups(nested)...) {
		fmt.Fprintf(out, "type %s struct { client *Client }\n\n", group.StructName)
		for _, op := range group.Operations {
			if typedSilverMethods[op.Namespace+"."+op.Name] {
				continue
			}
			fmt.Fprintf(out, "func (s *%s) %s(ctx context.Context, opts RequestOptions, out any) error {\n", group.StructName, exportedName(op.Name))
			fmt.Fprintf(out, "\treturn s.client.request(ctx, %q, %q, opts, out, true)\n", op.Method, op.Path)
			out.WriteString("}\n\n")
		}
	}
}

func writeClientFields(out *bytes.Buffer, groups []namespaceGroup) {
	out.WriteString("type generatedClientServices struct {\n")
	for _, group := range groups {
		fmt.Fprintf(out, "\t%s *%s\n", group.FieldName, group.StructName)
	}
	out.WriteString("}\n\n")
	for _, group := range groups {
		fmt.Fprintf(out, "type %s struct { client *Client }\n\n", group.StructName)
		for _, op := range group.Operations {
			fmt.Fprintf(out, "func (s *%s) %s(ctx context.Context, opts RequestOptions, out any) error {\n", group.StructName, exportedName(op.Name))
			fmt.Fprintf(out, "\treturn s.client.Request(ctx, %q, %q, opts, out)\n", op.Method, op.Path)
			out.WriteString("}\n\n")
		}
		writeAliases(out, group)
	}
}

func writeWireFunction(out *bytes.Buffer, golden []namespaceGroup, silver []namespaceGroup) {
	topLevelSilver, nestedSilver := splitNestedGroups(silver)
	out.WriteString("func wireGeneratedServices(client *Client) {\n")
	out.WriteString("\tclient.generatedClientServices = generatedClientServices{\n")
	for _, group := range golden {
		fmt.Fprintf(out, "\t\t%s: &%s{client: client},\n", group.FieldName, group.StructName)
	}
	out.WriteString("\t}\n")
	out.WriteString("\tclient.Silver = &SilverClient{\n")
	for _, group := range topLevelSilver {
		fmt.Fprintf(out, "\t\t%s: &%s{client: client},\n", group.FieldName, group.StructName)
	}
	for _, group := range nestedSilver {
		fmt.Fprintf(out, "\t\t%s: &Silver%sClient{\n", group.FieldName, group.FieldName)
		for _, child := range group.Children {
			fmt.Fprintf(out, "\t\t\t%s: &%s{client: client},\n", child.FieldName, child.StructName)
		}
		out.WriteString("\t\t},\n")
	}
	out.WriteString("\t}\n")
	out.WriteString("}\n\n")
}

func splitNestedGroups(groups []namespaceGroup) ([]namespaceGroup, []nestedNamespaceGroup) {
	topLevel := make([]namespaceGroup, 0, len(groups))
	byParent := map[string][]namespaceGroup{}
	for _, group := range groups {
		parent, child, ok := strings.Cut(group.Namespace, ".")
		if !ok {
			topLevel = append(topLevel, group)
			continue
		}
		group.FieldName = exportedName(child)
		byParent[parent] = append(byParent[parent], group)
	}
	parents := make([]string, 0, len(byParent))
	for parent := range byParent {
		parents = append(parents, parent)
	}
	sort.Strings(parents)
	nested := make([]nestedNamespaceGroup, 0, len(parents))
	for _, parent := range parents {
		children := byParent[parent]
		sort.Slice(children, func(i, j int) bool {
			return children[i].FieldName < children[j].FieldName
		})
		nested = append(nested, nestedNamespaceGroup{
			Namespace: parent,
			FieldName: exportedName(parent),
			Children:  children,
		})
	}
	return topLevel, nested
}

func flattenNestedGroups(groups []nestedNamespaceGroup) []namespaceGroup {
	var flattened []namespaceGroup
	for _, group := range groups {
		flattened = append(flattened, group.Children...)
	}
	return flattened
}

func writeInventoryFunctions(out *bytes.Buffer, golden []generatedOperation, silver []generatedOperation) {
	writeWrapperNames(out, "Golden", golden)
	writeWrapperNames(out, "Silver", silver)
}

func writeWrapperNames(out *bytes.Buffer, prefix string, ops []generatedOperation) {
	sort.Slice(ops, func(i, j int) bool {
		left := ops[i].Namespace + "." + ops[i].Name
		right := ops[j].Namespace + "." + ops[j].Name
		return left < right
	})
	fmt.Fprintf(out, "func %sWrapperInventory() []string {\n", prefix)
	out.WriteString("\treturn []string{\n")
	for _, op := range ops {
		fmt.Fprintf(out, "\t\t%q,\n", op.Namespace+"."+op.Name)
	}
	out.WriteString("\t}\n")
	out.WriteString("}\n\n")
}

func exportedName(value string) string {
	parts := strings.Fields(nonIdentifier.ReplaceAllString(value, " "))
	if len(parts) == 0 {
		return "Value"
	}
	for i, part := range parts {
		parts[i] = exportPart(part)
	}
	name := strings.Join(parts, "")
	if name == "" {
		return "Value"
	}
	if unicode.IsDigit(rune(name[0])) {
		name = "N" + name
	}
	return name
}

func exportPart(value string) string {
	if value == "" {
		return ""
	}
	runes := []rune(value)
	for i, r := range runes {
		if i == 0 {
			runes[i] = unicode.ToUpper(r)
			continue
		}
		runes[i] = unicode.ToLower(r)
	}
	return string(runes)
}

func fatal(format string, args ...any) {
	_, _ = fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
